-- MySQL Script generated by MySQL Workbench
-- lun 09 oct 2017 15:40:01 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tiendav2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendav2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendav2` DEFAULT CHARACTER SET latin1 ;
USE `tiendav2` ;

-- -----------------------------------------------------
-- Table `tiendav2`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`Sucursal` (
  `IdSucursal` INT(100) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) CHARACTER SET 'latin1' NOT NULL,
  `Direccion` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `Telefono` VARCHAR(9) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`IdSucursal`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`Proveedor` (
  `IdProveedor` INT(100) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) CHARACTER SET 'latin1' NOT NULL,
  `Telefono` VARCHAR(9) CHARACTER SET 'latin1' NOT NULL,
  `Direccion` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `NIT` VARCHAR(14) CHARACTER SET 'latin1' NOT NULL,
  `NRC` VARCHAR(7) CHARACTER SET 'latin1' NOT NULL,
  `Email` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`IdProveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`Compra` (
  `IdCompra` INT(100) NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `IdProveedor` INT(100) NOT NULL,
  `IdSucursal` INT(100) NOT NULL,
  `TipoCompra` CHAR(1) CHARACTER SET 'latin1' NOT NULL,
  `NumDocumento` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `Subtotal` DOUBLE NOT NULL,
  `IVA` DOUBLE NOT NULL,
  `Percepcion` DOUBLE NOT NULL,
  `Total` DOUBLE NOT NULL,
  PRIMARY KEY USING BTREE (`IdCompra`, `IdSucursal`, `IdProveedor`),
  INDEX `IdSucursal` (`IdSucursal` ASC),
  INDEX `IdProveedor` (`IdProveedor` ASC),
  CONSTRAINT `Compra_ibfk_1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `tiendav2`.`Sucursal` (`IdSucursal`),
  CONSTRAINT `Compra_ibfk_2`
    FOREIGN KEY (`IdProveedor`)
    REFERENCES `tiendav2`.`Proveedor` (`IdProveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`Producto` (
  `CodBarra` VARCHAR(13) CHARACTER SET 'latin1' NOT NULL,
  `Nombre` VARCHAR(30) CHARACTER SET 'latin1' NOT NULL,
  `Costo` DOUBLE NOT NULL,
  PRIMARY KEY (`CodBarra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`Inventario` (
  `IdSucursal` INT(100) NOT NULL,
  `CodBarra` VARCHAR(13) CHARACTER SET 'latin1' NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  INDEX `IdSucursal` (`IdSucursal` ASC),
  INDEX `IdSucursal_2` (`IdSucursal` ASC),
  INDEX `CodBarra` (`CodBarra` ASC),
  CONSTRAINT `Inventario_ibfk_1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `tiendav2`.`Sucursal` (`IdSucursal`),
  CONSTRAINT `Inventario_ibfk_2`
    FOREIGN KEY (`CodBarra`)
    REFERENCES `tiendav2`.`Producto` (`CodBarra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`DetalleCompra` (
  `IdCompra` INT(100) NOT NULL,
  `CodBarra` VARCHAR(13) CHARACTER SET 'latin1' NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  `CostoUnitario` DOUBLE NOT NULL,
  `IdSucursal` INT(100) NOT NULL,
  PRIMARY KEY USING BTREE (`IdCompra`, `CodBarra`, `IdSucursal`),
  INDEX `IdSucursal` (`IdSucursal` ASC),
  INDEX `CodBarra` (`CodBarra` ASC),
  CONSTRAINT `DetalleCompra_ibfk_1`
    FOREIGN KEY (`IdCompra`)
    REFERENCES `tiendav2`.`Compra` (`IdCompra`),
  CONSTRAINT `DetalleCompra_ibfk_2`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `tiendav2`.`Inventario` (`IdSucursal`),
  CONSTRAINT `DetalleCompra_ibfk_3`
    FOREIGN KEY (`CodBarra`)
    REFERENCES `tiendav2`.`Producto` (`CodBarra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`TipoPrecio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`TipoPrecio` (
  `IdTipoPrecio` INT(100) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) CHARACTER SET 'latin1' NOT NULL,
  `Utilidad` DOUBLE NOT NULL,
  PRIMARY KEY (`IdTipoPrecio`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`Venta` (
  `IdVenta` INT(100) NOT NULL AUTO_INCREMENT,
  `IdSucursal` INT(100) NOT NULL,
  `TipoVenta` CHAR(1) CHARACTER SET 'latin1' NOT NULL,
  `IdTipoPrecio` INT(100) NOT NULL,
  `Cliente` VARCHAR(30) CHARACTER SET 'latin1' NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `IVA` DOUBLE NOT NULL,
  `TotalGravado` DOUBLE NOT NULL,
  `Total` DOUBLE NOT NULL,
  `Direccion` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `Giro` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `NIT` VARCHAR(14) CHARACTER SET 'latin1' NOT NULL,
  `NRC` VARCHAR(7) CHARACTER SET 'latin1' NOT NULL,
  `NDocumento` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`IdVenta`, `IdSucursal`, `IdTipoPrecio`),
  INDEX `IdTipoPrecio` (`IdTipoPrecio` ASC),
  CONSTRAINT `Venta_ibfk_1`
    FOREIGN KEY (`IdTipoPrecio`)
    REFERENCES `tiendav2`.`TipoPrecio` (`IdTipoPrecio`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`DetalleVenta` (
  `IdVenta` INT(100) NOT NULL,
  `CodBarra` VARCHAR(13) CHARACTER SET 'latin1' NOT NULL,
  `Cantidad` DOUBLE NOT NULL,
  `PrecioUnitario` DOUBLE NOT NULL,
  `IdSucursal` INT(100) NOT NULL,
  PRIMARY KEY (`IdVenta`, `CodBarra`, `IdSucursal`),
  INDEX `IdSucursal` (`IdSucursal` ASC),
  INDEX `CodBarra` (`CodBarra` ASC),
  CONSTRAINT `DetalleVenta_ibfk_1`
    FOREIGN KEY (`IdVenta`)
    REFERENCES `tiendav2`.`Venta` (`IdVenta`),
  CONSTRAINT `DetalleVenta_ibfk_2`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `tiendav2`.`Inventario` (`IdSucursal`),
  CONSTRAINT `DetalleVenta_ibfk_3`
    FOREIGN KEY (`CodBarra`)
    REFERENCES `tiendav2`.`Producto` (`CodBarra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DetalleVenta_1`
    FOREIGN KEY (`IdSucursal`)
    REFERENCES `tiendav2`.`Sucursal` (`IdSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `tiendav2`.`Parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendav2`.`Parametro` (
  `IdParametro` INT(100) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(30) CHARACTER SET 'latin1' NOT NULL,
  `Valor` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`IdParametro`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
